#https://mherman.org/blog/dockerizing-a-react-app/
# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci 
RUN npm install react-scripts@3.4.3 -g 
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/build/config.js /usr/share/nginx/html/config_template.js
EXPOSE 80
CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/config_template.js > /usr/share/nginx/html/config.js && exec nginx -g 'daemon off;'"]
#CMD ["nginx", "-g", "daemon off;"]