# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

stages:
- stage: api_build
  displayName: Api Build
  jobs:  
  - job: CI
    displayName: Api Build    
    steps:
      - task: Docker@2
        displayName: Docker Build
        inputs:
          containerRegistry: '$(containerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'buildAndPush'
          Dockerfile: '$(dockerfilePath)'
          buildContext: '$(Build.SourcesDirectory)'
          tags: '$(tag)'

      - script: |
          export id=$(docker images --filter "label=test=true" -q | head -1)
          docker create --name testcontainer $id
          docker cp testcontainer:/testresults ./coveragereport
          docker rm testcontainer
        displayName: 'get test results'

      - script: |
          ls
          ls $System_DefaultWorkingDirectory
        displayName: 'get test results'  

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coveragereport/Cobertura.xml' 
          reportDirectory: '$(System.DefaultWorkingDirectory)/coveragereport'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/*.trx'
          mergeTestResults: true
          failTaskOnFailedTests: true

- stage: ui_build
  displayName: UI Build
  dependsOn: [] 
  jobs:  
  - job: ui_ci
    displayName: UI Build    
    steps:    
     - task: Npm@1
       inputs:
         command: 'install'
         workingDir: 'client'
         verbose: false
     
     - task: PowerShell@2
       displayName: Templatize Config File
       inputs:
         targetType: 'inline'
         script: |
           $configFilePath="client/public/config.js"
           $configDataRaw = (Get-Content $configFilePath -raw)
           $firstCurlyBrace = $configDataRaw.IndexOf('{')
           $length = $configDataRaw.Length
           $savedPrefixData = $configDataRaw.Substring(0,$firstCurlyBrace +1 )
           $configDataRaw = $configDataRaw.Remove(0,$firstCurlyBrace)
           
           $configDataJson =$configDataRaw | ConvertFrom-Json
           
           $outputFile = $savedPrefixData
           $configDataJson | Get-Member -MemberType NoteProperty | ForEach-Object {
                   $key = $_.Name
                   #Write-Host $key
                   $outputFile += "$key :'#{$key}#',"
               }
           
           
           $outputFile += "}"
           Write-Host $outputFile
           Write-Host $configFilePath
           Set-Content -Path $configFilePath -value $outputFile -Force
     - task: PowerShell@2
       displayName: Templatize Env File
       inputs:
         targetType: 'inline'
         script: |
            $envFilePath="client/.env"
            $envFile = (Get-Content $envFilePath -raw)
            $outputFile = ''            
            $envFile.Split("`n") | ForEach {
                $key = $_.Split("=")[0]
                $outputFile += "$key=#{$key}#" + "`n"
            }
             Write-Host $outputFile
             Set-Content -Path $envFilePath -value $outputFile -Force
     - task: Npm@1
       inputs:
         command: 'custom'
         workingDir: 'client'
         customCommand: 'run build'            
     - task: PublishBuildArtifacts@1
       displayName: Publish Artifacts
       inputs:
        PathtoPublish: 'client/build'
        ArtifactName: 'ui'
        publishLocation: 'Container'         

- stage: ui_deploy_dev
  displayName: Dev UI Deploy
  dependsOn: ui_build   
  variables:
   - group: ReactCICD-Dev 
  jobs:
  - deployment:  Deploy
    displayName: Deploy        
    environment: 'ui-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: replacetokens@3
            inputs:
              targetFiles: |
                $(Pipeline.Workspace)/ui/config.js
                $(Pipeline.Workspace)/ui/**/*.js
                $(Pipeline.Workspace)/ui/**/*.html
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'fail'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTelemetry: true
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here                
                ls
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/ui'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Pipeline.Workspace)/ui-$(Build.BuildId).zip'
              replaceExistingArchive: true
              verbose: true

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'VS Ultimate'
              appType: 'webAppLinux'
              WebAppName: 'nnepal-react-wc-dev'
              packageForLinux: '$(Pipeline.Workspace)/ui-$(Build.BuildId).zip'
              StartupCommand: 'pm2 serve /home/site/wwwroot/ui --no-daemon --spa'

- stage: api_deploy_dev
  displayName: Dev API Deploy
  variables:
   - group: ReactCICD-Dev
  dependsOn: api_build     
  jobs:
  - deployment:  Deploy
    displayName: Deploy        
    environment: 'api-dev'
    strategy:
      runOnce:
        deploy:
          steps: 
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'VS Ultimate'
              appType: 'webAppLinux'
              WebAppName: 'nnepal-react-wc-api-dev'
              packageForLinux: '$(Pipeline.Workspace)/api/**.zip'              

          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: 'VS Ultimate'
              appName: 'nnepal-react-wc-api-dev'
              resourceGroupName: 'demo-appconfig-01'
              connectionStrings: |
                [
                   {
                    "name": "Database",
                    "value": "$(ConnectionStrings_Database)",
                    "type": "SQLAzure",
                    "slotSetting": false
                   }
                  
                ]