# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

stages:
- stage: api_build
  displayName: Api Build
  jobs:  
  - job: CI
    displayName: Api Build    
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'api'
        publishLocation: 'Container'

- stage: ui_build
  displayName: UI Build
  dependsOn: [] 
  jobs:  
  - job: ui_ci
    displayName: UI Build    
    steps:
     - task: Bash@3
       inputs:
         targetType: 'inline'
         script: |
           # Write your commands here
           
           ls
     - task: Npm@1
       inputs:
         command: 'install'
         workingDir: 'client'
         verbose: false
     - task: Npm@1
       inputs:
         command: 'custom'
         workingDir: 'client'
         customCommand: 'run build'
     
     - task: PublishBuildArtifacts@1
       displayName: Publish Artifacts
       inputs:
        PathtoPublish: 'build'
        ArtifactName: 'ui'
        publishLocation: 'Container'         